package com.pulsehub.dto.request;

import com.pulsehub.entity.enums.CallSignalType;

/**
 * {@code callId} is generated by the caller's browser and identifies one call
 * attempt end to end. {@code payload} is the JSON-serialized SDP description
 * (OFFER/ANSWER) or ICE candidate (ICE_CANDIDATE) — opaque to the server,
 * which only relays it.
 */
public record CallSignalRequest(
        Long conversationId,
        String callId,
        CallSignalType type,
        String payload
) {
}
